### ISSUE TITLE
Add placeholder / feedback when placing assets

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#122]
When placing an asset, it can take a moment until the server responds whether the placement is allowed and (if yes) places the asset.

We should spawn a placeholder immediately after clicking. If the placement is okay, it is replaced with the real asset. If not, we display some sort of feedback that the asset could not be placed at that position.

**Comment by kb173** [comment]
Since we can fully depend on the Lego board (which has multiple alternative solutions if the lego detection itself does not work), this is not necessary for now. It would be good to add in the future though.

**Comment by MathiasBaumgartinger** [comment]
We should further discuss if we want to avoid the server managing assets in the client, but much rather the client itself should have a connection to the database (@chrisgraf).

If we want a feedback we could possible make the asset transparent for as long as the server not accepting it.

**Comment by MathiasBaumgartinger** [comment]
This problem was solved by the item-spawner not simply sending a request but much rather appending a new node to the corresponding AssetHandler, which handles the request:

As the server request takes some time we instance a scene for the time we are waiting for a result
* Sucessful: the node will be renamed with the given id of the server which was sent in the json. Thus the assethandler will not instanciate a second asset at the given position.
* Unsucessful: The attached node with the temporary asset will be removed.

Commit 773f4567f14fcaac06d4ee3a0b785b62b203c237 was a first implementation, with 33b876052e16d1eb51895d698049d9deb7d44452 this is fully implemented. On demand we could change the material from ``DebugPink.tres`` to a more fitting material.
