### ISSUE TITLE
Load Error: res://Resources/water_normal.png::Texture

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#18]

**Comment by kb173** [comment]
This image can be used:

![water_normal](https://user-images.githubusercontent.com/18697097/55753117-da1da880-5a49-11e9-92fb-7661aef5452e.png)

However, this issue also asks a broader question: Since the pipeline of getting textures from the server is well implemented and used, should we move all image resources, including this one, there?

The detailed ground textures, for example, are similar in nature to this one (they even have normal maps as well), and those are fetched from the server.

**Comment by chrisgraf** [comment]
currently this has to be set up manually - for the future this should be shipped with the server, as you proposed..

**Comment by chrisgraf** [comment]
closing as the client resources are included now via network share
