### ISSUE TITLE
missing check if image really exists

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#20]
I get a lot of these errors:

E 0:02:30:0804   Condition ' texture->data_size == 0 && !texture->render_target ' is true. returned: Ref<Image>()
  <C Source>     drivers/gles3/rasterizer_storage_gles3.cpp:1059 @ texture_get_data()

presumably because the image which is tried to get loaded does not exist or is empty .. we have to check for that...

**Comment by kb173** [comment]
08677cb added a check to verify whether the file which is supposed to be loaded as an image exists, which may fix this.

If you can verify that this fixed the errors, the issue can be closed. (I don't seem to be missing any Images, so I can't test it myself.) If not, the problem may be in the `ImageTexture.load()` - this function isn't well documented, and it's unclear what happens when loading a path which does exist, but isn't an image...

**Comment by kb173** [comment]
https://github.com/boku-ilen/landscapelab/commit/f5d486bdf7ef62ac9776116efe3bbf517ba92707 now also exits the function if the path does not exist - thus, only the logger warning should be shown now.
