### ISSUE TITLE
vegetations seems to produce blue artefacts

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#21]
at least on windows

**Comment by kb173** [comment]
I assume this happens when (part of) the vegetation data is missing - particles are instantiated, but their texture is invalid.
I'll add a check which disables the particle emitters if there was no result.

Could the data be missing due to some path inconsistency between server and client? It does seem like spritesheets, distributions, etc. are being properly generated on the server...

**Comment by chrisgraf** [comment]
I will investigate the server path but still if vegetation data is missing it should not result in these blue artefacts

**Comment by chrisgraf** [comment]
the server paths are now fixed - it still seems that there are a lot of pytho_c_ids which currently are not in the database fixtures and therefor not found. If this is currently intentional we can close this...

**Comment by chrisgraf** [comment]
[2019-05-11 17:04:16.478] ERROR: HTTP client: got 404 as http status which indicates missing data or a bug in the request url: /vegetation/151/1
[2019-05-11 17:04:17.510] ERROR: HTTP client: got 404 as http status which indicates missing data or a bug in the request url: /vegetation/100/1
[2019-05-11 17:04:17.936] ERROR: HTTP client: got 404 as http status which indicates missing data or a bug in the request url: /vegetation/126/1

**Comment by kb173** [comment]
Yes, the current fixture on the server only defines some of the possible phytocoenosis IDs, so those errors are normal.

**Comment by kb173** [comment]
Since the vegetation path was fixed and 805c645 and e8c3a21 also made changes to make the vegetation more performant and robust, which may also fix the problem that caused the artifacts to appear in that case, I am closing this issue.
