### ISSUE TITLE
use surface terain model for low LOD especially for woods

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#233]
in low LOD situations with a certain distance to the player we don't render billboards anymore but just use the surface model to add volume to woods in the distance. This could be assisted by adding certain single trees along the far horizon?

the smooth transition between the billboard rendering and this new mode in motion has to be figured out

**Comment by kb173** [comment]
With https://github.com/boku-ilen/landscapelab/commit/a4c938f2d12dba42ee69a8394ebd25fbd0caaf62, the nDSM is added to the DTM height at a distance. This works reasonably well, but it's important that the building radius is not larger than the nDSM application radius, since the terrain will clip into buildings otherwise. (Currently these factors are both 800.) There are other considerations too, though, such as vegetation which may stop at a smaller radius.

Should we define a global "detail" radius which we try to use for buildings, nDSM, and large trees? Alternatively, we could only apply nDSM values if the land-use map has a certain value to differentiate between vegetation and buildings, but imo that's likely to result in artifacts due to limited resolution.
