### ISSUE TITLE
random crash after some time (related to freed tiles still referenced)

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#25]
![worldtile_67](https://user-images.githubusercontent.com/1245084/57245803-06721800-703c-11e9-9aef-1ffcf8e77470.png)

Maybe we have to track references to tiles somewhere and only free them after no more references exist OR we have to check everywhere for the existence of the tile when we use it as they could be freed anytime in the process
Is it possible in Godot to fetch these exceptions and handle them without a crash?

**Comment by kb173** [comment]
Unfortunately, Godot has no exception handling at all.

However, our design should actually make it impossible for this to happen. There are two possibilities of why this errors is occurring: Either the `WorldTile.delete()` function is still not completely safe (https://github.com/boku-ilen/landscapelab/commit/695acdecd11a21cc030ee13a447867ffd8e273aa should've fixed this, but the solution has to be refactored, as evident in https://github.com/boku-ilen/landscapelab/commit/e4541abae395bb5c69304756e9450ce041f51356), or there's thread unsafety somewhere else (likely in a Module) which causes this to happen.

For the first point, I will refactor `WorldTile.delete()` and the logic around it.
Regarding the second point, I believe that `WorldTile.get_texture_recursive()` is potentially thread-unsafe (and, due to cropping an image, hard on performance). Once all graphics are properly cropped on the server, the function will be obsolete, and this potential cause of thread unsafety will be fixed.

**Comment by kb173** [comment]
With 123f6cd, `get_texture_recursive` has been removed, and the server now does all cropping. This should fix that potential cause of thread unsafety, but it seems like as expected, `WorldTile.delete()` and the WorldTile visibility is the main culprit here, especially since I can only reproduce this issue when moving around.

This makes sense, since there's likely a race condition in the tile visibility, and that visibility is used in `is_leaf_tile()`! Presumably, that race condition can cause tiles to still be invisible when they should be visible (since the children tiles converged), and thus, `is_leaf_tile()` also returns false when it should be true on that tile.
As mentioned, this will be refactored.

**Comment by kb173** [comment]
After https://github.com/boku-ilen/landscapelab/commit/d08fbe235ba91fd0a712f417141c98ed3d9a46a6 and https://github.com/boku-ilen/landscapelab/commit/c660285632b355092f9781d3f4e8ea44d84167ce, in which functions related to tile visibility, deletion and splitting have been updated, I can no longer reproduce the issue.

@chrisgraf, if you can verify this as well, I think the issue can be closed.

**Comment by kb173** [comment]
The same goes for #22 and #24, which should be fixed now as well - all these issues had the same underlying cause.

**Comment by chrisgraf** [comment]
at least the crash is not there anymore .. we can close this after some more experience with the new commits

**Comment by chrisgraf** [comment]
![image](https://user-images.githubusercontent.com/1245084/58097486-cda77680-7bd7-11e9-8f70-162cc1674667.png)

still there :/

**Comment by chrisgraf** [comment]
did not reappear .. seems to be fixed
