### ISSUE TITLE
Handle input in the UI and the World correctly

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [boku-ilen/landscapelab#250]
The Editor-styled UI brings new challenges in the input-handling. In my opinion the input controls for moving (WASD, Mouse dragging) and changing the lookat (Mouse controls) should only be registered by the part of the UI that is currently "selected".

 @kb173 what do you think?

**Comment by kb173** [comment]
After some testing I think the best solution would be this:

- Let the player handle input via the `_input` function (__not__ `_unhandled_input` as right now, since that seems to block input when used in a `ViewportContainer`).
- In the `ViewportContainer`, react to the `focus_entered` and `focus_exited` signals and set the `disable_input` flag of its `Viewport` child node accordingly.

That way, we can handle input as we normally would, and the 3D visualization only receives input if it should (if the UI element is focused).

**Comment by MathiasBaumgartinger** [comment]
Originally i wrote something like:

> I liked the idea of this, however it seems we run into another problem here.
> 
> For the movement of the player (related to #243, #80, #72) another problem appeared. Since the input was handled seperately in the ``_process`` function i moved the functionality to the ``_handle_general_input(event)`` using a dictionary. This however only works with the function you explicitly called not to use ``_unhandled_input``, in any other way it will again register each keystroke, even those which were not meant for the player movement.

However, it seems like this is just a bit ... clunky behaviour. After doing some testing i can say it worked for me half of the time - didn't work the other half. I have added a few things and it now looks pretty stable - I will tag this as ``needs testing`` for now anyways.

**Comment by MathiasBaumgartinger** [comment]
I think this is already fixed, leaving it for a meeting discussion in a meeting together though.

**Comment by kb173** [comment]
Seems to me like this is working as intended now. @MathiasBaumgartinger can you confirm (and close the issue if you agree)?

**Comment by MathiasBaumgartinger** [comment]
Yeah - I think this has sufficiently been tested. Closing ...
