### ISSUE TITLE
crash after editor change (relates to godot bug)

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#29]
![image](https://user-images.githubusercontent.com/1245084/57248744-6f10c300-7043-11e9-8cc7-fafc62c9976b.png)

just load the client and wait .. here it happened after 15-30min

**Comment by chrisgraf** [comment]
![image](https://user-images.githubusercontent.com/1245084/57248816-a5e6d900-7043-11e9-87e3-9ea578ddb86a.png)

**Comment by chrisgraf** [comment]
this probably has to do with running it in the editor .. if something is changed in the editor in windows the crash is reproducable...

**Comment by kb173** [comment]
Yes, making a change in the editor seems to cause most Godot projects to crash at the moment, I've had the same experience with another project. So this is most likely a problem with Godot itself, which shouldn't pose any problems when running the exported project.

I've looked at most parameters in the debugger, and they all stay constant when leaving the game open and not moving, so there shouldn't be any leak that can cause something like this to happen.

Can the issue be closed since it's an editor-only problem of Godot itself?

**Comment by chrisgraf** [comment]
We have to verify a longrun in an exported project to be sure

**Comment by chrisgraf** [comment]
related to godotengine/godot#28398

**Comment by chrisgraf** [comment]
as I did not experience this issue with godot 3.2 and the godot issue was fixed I close this
