### ISSUE TITLE
limitation: currently dynamically generated models can not have functionallity in client

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#32]
this affects buildings for instance, which can not have PV-modules currently. We have to revisit how to dynamically import models into godot

**Comment by kb173** [comment]
We could load the dynamically loaded scene as a child of a new controller scene, which can be specified based on the asset type.

**Comment by kb173** [comment]
All building scenes have this format:

```
- Scene Root
    - Main mesh
    - Roof mesh
```

The roof mesh has a material with a texture which we could access and modify by walking along the scene tree according to this specification.

This seems like a somewhat fragile solution, since we always require this exact format. However, the alternatives which I can think of would require extending each of the thousands of building scenes, which is really inefficient. Is it viable to have strictly defined scene tree formats for each dynamic asset which needs extra functionality?

**Comment by kb173** [comment]
There is also a problem with simply replacing the texture: It would place PV modules on all sides of the roof. I think that to prevent this, we'll need to use a spritesheet for the roof which includes the normal roof and the roof with a PV panel (if it's activated - otherwise also the normal roof). The south side should access the PV part of the UV map, the rest the normal part.

This will have to be done in the building generation python script.

**Comment by chrisgraf** [comment]
As discussed we will currently not implement this but provide an icon above the affected rooftops

**Comment by chrisgraf** [comment]
Additionally we need to detect the associated KG for which the rooftop PV should be enabled

**Comment by chrisgraf** [comment]
this feature will not be implemented in 0.4

**Comment by kb173** [comment]
We could treat buildings like all other assets (which are purely on the client) and simply make that asset itself load the dynamically generated model. This would unify the handling of all assets, solve this issue and not introduce much added complexity.

**Comment by kb173** [comment]
This would require some restructuring in the server and the client. Should probably be done together with https://github.com/boku-ilen/landscapelab-server/issues/3

Might be relevant for the near future since we want to e.g. be able to fill buildings with additional data which can be displayed in various ways (tooltip, shader, ...)

**Comment by chrisgraf** [comment]
buildings and other assets which also may hold additional data that parameterize their appearance or which should be displayed are now handled by the client via geodot

so this is closed
