### ISSUE TITLE
flickering on the border between two tiles in some distance

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#36]
maybe a zbuffer problem or an issue with different heights? (I also noticed that there is a little step between those tiles)

**Comment by kb173** [comment]
This is because tiles have a skirt around them to prevent "holes" when a high LOD tile is next to a low LOD tile, since those can't perfectly line up. The flickering is most likely due to the z-buffer, as you said.

I assume the problem you're describing mostly/only happens on low LOD tiles? If so, that could be fixed by moving the skirt closer towards the edge of the actual tile. However, to do this, we would need some more complex logic when generating those meshes (currently, we can use Godot's default plane mesh).  Another option would be to increase the subdivision count, although this could hinder performance if we want to render many tiles at low LODs.

**Comment by chrisgraf** [comment]
for me this does not occur anymore (at least I recently could not reproduce this)
