### ISSUE TITLE
sometimes in the ThreadPool an instance does not exist any more even if in the line above a null check succeded

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#39]
![image](https://user-images.githubusercontent.com/1245084/57872954-3fb14180-780d-11e9-8e1c-cd2bdefd5f5d.png)

**Comment by kb173** [comment]
In [this answer](https://godotengine.org/qa/10085/how-to-know-a-node-is-freed-or-deleted), it is suggested to check the node like this:

```
var wr = weakref(node)
if (!wr.get_ref()):
    # freed
else:
    # not freed
```

Perhaps we need to do something like that as well. It feels a bit hacky though...

It would be best if we can find out what is causing this - by design, tiles should never be freed if they still have modules which are not done loading, so it's likely that they're crashing somewhere else.

**Comment by chrisgraf** [comment]
Yes agreed, still we have to stabilize the code so errors don't crash the engine and maybe it helps to get a better understanding of what is really happening

**Comment by kb173** [comment]
In aa04b41, the proposed fix was implemented. I can't currently reproduce the error though, so we still need to test whether this is really an improvement.

**Comment by chrisgraf** [comment]
the error did not reappear - seems fixed
