### ISSUE TITLE
scaling of ground texture is incorrect in relation to each other

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#46]
![image](https://user-images.githubusercontent.com/1245084/58108985-0d2c8d80-7bed-11e9-9f47-afe459109730.png)

**Comment by chrisgraf** [comment]
at least ground textures seem to small .. maybe trees too?

**Comment by chrisgraf** [comment]
ground textures current are just mock ups and will be replaced later with more meaningful values

**Comment by kb173** [comment]
The maximum plant size (and thus mesh size) of vegetation layers has been made easier to modify and set to the current values in d85e5eb. This means that plants should now be exactly `avg_size` (from the spreadsheet) large. I verified this by approximately measuring it with a tree texture, and it seems to be good.

3e7a42c added an option for the detail ground texture scale. I think the current value looks good, but it can now be easily tweaked if we decide otherwise.
