### ISSUE TITLE
Interpolation of height calculation isn't 100% precise

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#56]
![image](https://user-images.githubusercontent.com/1245084/58753462-bd3ca900-84bf-11e9-8c78-31707dde38a6.png)

**Comment by kb173** [comment]
Did you collide at that point, or could you go down even further?

If you did collide at some point, this may just be due to the collision mesh being pretty imprecise (noticeable at relatively low LODs) - we could expand that code to make it more exact, or to be able to specify that in the settings.

**Comment by chrisgraf** [comment]
its colliding at some point .. so it's the mentioned inprecision

**Comment by kb173** [comment]
The precision of the collision mesh can now be specified in the settings with 6232127. This fixes some problems, however, this particular issue remains, since the player doesn't use the collision mesh, but the actual pixel value.

I will test whether it's feasible to make the collision mesh precise enough, and only use that instead of the pixel values. Otherwise, we will have to interpolate the height values to provide smooth gradients from pixel to pixel.

**Comment by kb173** [comment]
Interpolation has been added in 98b51b3. This makes movement on the ground smoother  and makes this problem less frequent, but it's still there. I believe that this could be due to the mesh quads not actually being bilinear, like the interpolation, because they're laid out like this after triangulation:

```
 ___
|  /|
| / |
|/__|
```

Interpolating like this would be more complex, but doable.

It could also be something related to an offset or scaling - I have tested various changes in that direction with no good results, but the way this behaves makes it look like an offset issue sometimes.

Re-implementing wireframes (#55) would probably help with debugging this.

**Comment by kb173** [comment]
8d41f3a fixes the issue which I described as seeming like an offset. This further reduces the extent of this problem. After some more testing, I'm almost certain that the remaining cases are caused by the triangle problem described above.

**Comment by chrisgraf** [comment]
it's definitely better now

**Comment by chrisgraf** [comment]
very seldomly

https://cdn.discordapp.com/attachments/508352162598748171/591371390075142159/unknown.png
