### ISSUE TITLE
trees are a bit above the ground sometimes

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#58]
![image](https://user-images.githubusercontent.com/1245084/58753626-58368280-84c2-11e9-8141-9e642aacf860.png)

**Comment by kb173** [comment]
`get_height_at_position()` from the TerrainColliderModule now implements custom bilinear filtering. I believe that we could fix this issue by implementing that algorithm in the vegetation particle shader as well, since this problem most likely stems from the lack of smooth gradients between height data points in their placement logic.

Godot does provide filtering in the Texture class, however this does not work for our custom RGB heightmap format.

**Comment by chrisgraf** [comment]
@kb173 : implementing a negative offset for assets so that there is a little threshold to prevent "flying" trees based on LOD
@chrisgraf : finalize the high quality height map

**Comment by kb173** [comment]
bd0f8573cfc2cf6151018c35ea3c12b74f5048ee improved this for me. The shader variable for an optional offset was added as well, but if it's not necessary, it's better to leave it as precise as possible in my opinion.

@luxkon Can you pay attention to floating vegetation as well, and report back if you do see it somewhere?

**Comment by kb173** [comment]
Only possible remaining problem for this is #141
