### ISSUE TITLE
limitation: currently only a certain amount of tiles are displayed 

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#59]

**Comment by kb173** [comment]
This just requires a productive setting for the tile spawn radius.

~340km is the maximum view distance that makes any sense, ~250km should be perfectly fine.

**Comment by chrisgraf** [comment]
we will push the productive settings soon, if other local settings are required they will be kept locally

**Comment by chrisgraf** [comment]
@luxkon : we need the realistic an performant values for the maximum view distance (max haze, nr of tiles)

**Comment by luxkon** [comment]
done and checked with karl

**Comment by kb173** [comment]
The settings we deemed good (loads relatively quickly, but is likely enough visually) were made in dc941f8. The haze was also adapted.

I noticed that we were actually loading more tiles than were visible, which was fixed in 3c52453. (There is no visible change, but the performance and loading times are better). We now have a view distance of 60km in each direction. This is already going to be at the limit of some of our data, so it's most likely enough.

@chrisgraf @MathiasBaumgartinger Don't forget to change the tile-spawn-radius to 1-2 tiles and the view distance to 10-20km locally when debugging.
