### ISSUE TITLE
limitation: code in view rotate is duplicated and needs cleanup

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#72]
While the VR mode is disabled you should be able to "move your head" with standard controls. Best would be to use the same mouse commands as in 3rd person view. They just have to be disabled as per our agreement while VR-mode is enabled.

**Comment by chrisgraf** [comment]
I added a quick fix to enable rotation to 1st person view in a1a57d40e6a6f07bd7c78abca3e9a254b6cbceb8
However the input handling code should be more generalized in AbstractPlayer I think .. and the check if the input belongs to the viewport the mouse is currently over needs an improvement, as also the hidden underlying viewport currently gets the input signals

**Comment by kb173** [comment]
In https://github.com/boku-ilen/landscapelab/commit/b3b33bb81883cff680bdbfc549660b35afaa5723, everything that was completely identical was moved to AbstractPlayer. Some new functions were introduced:

`_handle_abstract_general_input` and `_handle_abstract_viewport_input` handle the input which is identical for all Perspectives in AbstractPlayer. The first takes all input, the second only input within that viewport.

The similar `_handle_general_input` and `_handle_viewport_input` can be overridden to extend the functionality provided in AbstractPlayer.

The `rotating` functionality isn't generalized yet, since it has a similar purpose in both perspectives, but works differently (the first person perspective has the additional 'Head' node).

**Comment by kb173** [comment]
#243 removed this duplication
