### ISSUE TITLE
Add ability to get specific LOD images for Minimap Zoom

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#75]
- zooming out stops at some point
- the different LOD-tiles are not used

**Comment by kb173** [comment]
The maximum zoom-out can be changed with the "zoom_max" setting.

Using different LOD-tiles is tricky: Since the minimap tiles are simply modules of the world terrain, their LOD matches the LOD of the world tiles (meaning high LOD close to the player).

What we could do is add visibility layers for each level of detail. That way, cameras can decide for themselves whether they want to display the highest loaded LOD, or something below that.

**Comment by kb173** [comment]
Also needs to be added to Geodot (ability to request a specific LOD)

**Comment by kb173** [comment]
Solved by the new minimap implementation (2D layer with a single LOD)
