### ISSUE TITLE
VR does not work and does not issue a proper error message why it does not work

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#83]
clear installation (test server) incl. oculus drivers (oculus without godot works) .. is there some configuration missing? vr button does nothing

**Comment by kb173** [comment]
Sorry, I forgot this for the setup process since it was already given on my machine: Godot uses the OpenVR API, which Oculus does not include by default. SteamVR is the standard (and only?) user interface and runtime for OpenVR, so we will have to install Steam and go through the SteamVR setup there.
It should work once SteamVR is up and running.

**Comment by chrisgraf** [comment]
Ok will try that - but there still should be a reasonable error message in my point of view

**Comment by kb173** [comment]
7f3eaed added error messages and also wired the perspective with the UI signals - it seems like it was only the keyboard shortcut previously.

**Comment by kb173** [comment]
Tested, working now!
