### ISSUE TITLE
client is requesting lod levels which are not prepared resulting in error messages

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#86]
can we have a minimum lod level below which no request is issued? (LOD 1-10 for instance) so not to flood the logs? 

Or should/can we provide these files?

**Comment by kb173** [comment]
Which request is it exactly? I can't think of a situation where that could happen, unless the start LOD setting has been changed...

If it's just the server getting errors like `get_cropped_for_next_tile requires a tile to exist at {}!` with low LODs, that's likely because it's trying to crop from a non-existent tile. E.g. if the client requests a tile at level 13 and it's not available, the server tries 12, 11, 10, ... At some point (after `MAX_STEP_NUMBER` in `tiles.py`) the server stops and either generates the cropped tile if something was found, or informs the client that no tile was available.

**Comment by chrisgraf** [comment]
double escaped path looks weird in the logs, local write permissions should be available but if they are not a proper error message should be given

**Comment by kb173** [comment]
The (main) cause was a wrong path in the server settings. Regardless, the error message has been improved in https://github.com/boku-ilen/landscapelab-server/commit/8042ec96d36e797cb8034c39770a693212b3abbc, and the paths have been cleaned up in https://github.com/boku-ilen/landscapelab-server/commit/ae152254bda6870dfe8a181291995896c850380e.
